name: figmage_package_generator
description: A generator for an empty figmage styles dart package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason: ^0.1.0-dev.51
  package_config: ^2.1.0

dev_dependencies:
  lintervention: ^0.1.1
  mocktail: ^1.0.0
  test: ^1.19.2
