name: figmage
description: A CLI tool for generating Figma styles for Flutter
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  figma: ^7.0.0
  mason_logger: ^0.2.5
  pub_updater: ^0.3.0
  source_gen: ^1.4.0
  
dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  test: ^1.24.2
  lints: ^2.1.1
  mocktail: ^1.0.0
  melos: ^3.1.1
