name: figmage
description: A CLI tool for generating Figma styles for Flutter
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.4.0
  figma: ^7.0.0
  mason_logger: ^0.2.5
  pub_updater: ^0.3.0
  source_gen: ^1.4.0
  figmage_package_generator:
    path: packages/figmage_package_generator
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  figma_variables_api:
    path: packages/figma_variables_api
  collection: ^1.18.0
  code_builder: ^4.7.0
  build: ^2.4.1
  dart_style: ^2.3.3
  
dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  build_version: ^2.1.1
  test: ^1.24.2
  lints: ^2.1.1
  mocktail: ^1.0.0
  melos: ^3.1.1
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  build_test: ^2.2.1
