name: figmage
description: A CLI tool for generating Figma styles for Flutter
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  figmage_api:
    git:
      url: https://github.com/whynotmake-it/figmage.git
      path: packages/figmage_api

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.19.2
  melos: ^3.1.1
