name: figmage
description: A CLI tool for generating Figma styles for Flutter
version: 0.1.0-dev.4
repository: https://github.com/whynotmake-it/figmage
issue_tracker: https://github.com/whynotmake-it/figmage/issues
website: https://whynotmake.it/figmage

executables:
  figmage:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.5.0
  code_builder: ^4.10.0
  collection: ">=1.17.2 <2.0.0"
  dart_style: ^2.3.4
  equatable: ^2.0.5
  figma_variables_api: ^0.1.0-dev.4
  figmage_package_generator: ^0.1.0-dev.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mason_logger: ^0.2.5
  meta: ">=1.9.1 <2.0.0"
  path: ^1.8.3
  pub_updater: ^0.4.0
  riverpod: ^2.4.6
  source_gen: ^1.4.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.1
  build_version: ^2.1.1
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  lintervention: ^0.1.1
  melos: ^5.3.0
  mocktail: ^1.0.0
  test: ^1.24.2
