// Mocks generated by Mockito 5.4.4 from annotations
// in figma_variables_api/test/src/client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:figma_variables_api/src/client.dart' as _i3;
import 'package:figma_variables_api/src/models/dto/variable_response/variables_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVariablesResponseDto_0 extends _i1.SmartFake
    implements _i2.VariablesResponseDto {
  _FakeVariablesResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FigmaClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFigmaClient extends _i1.Mock implements _i3.FigmaClient {
  MockFigmaClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get useHttp2 => (super.noSuchMethod(
        Invocation.getter(#useHttp2),
        returnValue: false,
      ) as bool);

  @override
  String get accessToken => (super.noSuchMethod(
        Invocation.getter(#accessToken),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#accessToken),
        ),
      ) as String);

  @override
  String get apiVersion => (super.noSuchMethod(
        Invocation.getter(#apiVersion),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#apiVersion),
        ),
      ) as String);

  @override
  bool get useOAuth => (super.noSuchMethod(
        Invocation.getter(#useOAuth),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<Map<String, dynamic>> authenticatedGet(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatedGet,
          [url],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.VariablesResponseDto> getLocalVariables(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalVariables,
          [key],
        ),
        returnValue: _i5.Future<_i2.VariablesResponseDto>.value(
            _FakeVariablesResponseDto_0(
          this,
          Invocation.method(
            #getLocalVariables,
            [key],
          ),
        )),
      ) as _i5.Future<_i2.VariablesResponseDto>);
}
