name: figma_variables_api
description: Figma REST API for variables.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  http2: ^2.0.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  collection: ^1.17.2
  copy_with_extension: ^5.0.2

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.19.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  markdown: ^7.1.0
  args: ^2.4.1
  yaml: ^3.1.2
  mockito: ^5.4.2
  
