name: figma_variables_api
description: Figma REST API for variables.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.19.2
  
