name: figmage_api
description: The Figma API client for figmage
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  freezed: ^2.4.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.19.2
dependencies:
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
