name: Continuous Integration

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # push:
  #  branches:
  #    - main
  pull_request:
    branches:
      - main

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  flutter-check:
    name: Build Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v4

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1.6.0
        with:
          sdk: 'stable'

      - name: Ⓜ️ Set up Melos
        uses: bluefireteam/melos-action@v3

      - name: 🧪 Run Analyze
        run: melos run analyze

      - name: 📝 Run Test
        run: melos run coverage

      - name: 📊 Generate Coverage
        id: coverage-report
        uses: whynotmake-it/dart-coverage-assistant@825dd99025d7e29a5b2b65eadea79c38e47ebfa2
        with:
          enforce_threshold: 'single'
          enforce_forbidden_decrease: 'none'
          lower_threshold: 50
          upper_threshold: 90
